### ISSUE TITLE
Issues on export

### ISSUE THREAD

**Issue by balaramsudip** [Jacocococo/MCData#1]
When I clicked export I got a null pointer exception : 
java.lang.NullPointerException
	at com.jacoco.mcdata.Deobfuscation.export(Deobfuscation.java:46)
	at com.jacoco.mcdata.Gui$5.actionPerformed(Gui.java:201)
	at java.desktop/java.awt.Button.processActionEvent(Button.java:411)
	at java.desktop/java.awt.Button.processEvent(Button.java:379)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by balaramsudip** [comment]
On windows it works, i am going to leave this open for the mac only users

**Comment by Jacocococo** [comment]
The error happened when trying to specify the path, in which the .jar shall be exported to. Did you use the default path? If you did, try to set it to a different path

I also don't have any device with MacOS, so I can't try it for myself

**Comment by ghost** [comment]
I have a MacOS system, can you please explain a bit more?

**Comment by Jacocococo** [comment]
Do you experience the same problem, when trying to Export a deobfuscated jar?

**Comment by ghost** [comment]
> Do you experience the same problem, when trying to Export a deobfuscated jar?

Yeah, but it's a different error apparently about:
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -1

**Comment by Jacocococo** [comment]
Can you please send me the full exception using pastebin? I need more information to debug this

**Comment by ghost** [comment]
> Can you please send me the full exception using pastebin? I need more information to debug this

When I put the destination for 1.16.2:
```
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at com.jacoco.mcdata.files.MapLocation.<init>(MapLocation.java:33)
	at com.jacoco.mcdata.Gui$2.mouseClicked(Gui.java:118)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.TextComponent.processEvent(TextComponent.java:673)
	at java.awt.TextField.processEvent(TextField.java:588)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

When I press 'Export':
```
java.lang.NullPointerException
	at com.jacoco.mcdata.Deobfuscation.export(Deobfuscation.java:46)
	at com.jacoco.mcdata.Gui$4.actionPerformed(Gui.java:183)
	at java.awt.Button.processActionEvent(Button.java:409)
	at java.awt.Button.processEvent(Button.java:377)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Also, I may add: MacOS is different for file destinations, instead of (file)\Sources\Export for us its' (file)/Sources/Export, I recommend you should do something in the code to check if its a certain OS, then make these files to work for us, but I doubt this will make a difference.

**Comment by Jacocococo** [comment]
I have made a pre-release for v1.1.1, which hopefully fixes this issue. Please check if it works, and if it does, I'll remove the pre-release tag.

**Comment by ghost** [comment]
> I have made a pre-release for v1.1.1, which hopefully fixes this issue. Please check if it works, and if it does, I'll remove the pre-release tag.

Got it, I'll reply if anything else happens.

**Comment by ghost** [comment]
> I have made a pre-release for v1.1.1, which hopefully fixes this issue. Please check if it works, and if it does, I'll remove the pre-release tag.

It works perfectly, however, there is one slight problem but it isn't a big deal:
It creates the Source (and Export) folder, but it's like /Users/me/Documents/Projects/TestingMCData/Sources/Export, but eitherway than that, it works fine. Thank you!

**Comment by Jacocococo** [comment]
That's great to hear!

I'll see what I can do about the path, but for now, you can just manually change the export path, if you don't like the default path.
